// A simplified demonstration of signal SIGFPE

#include <stdlib.h>			// Libraries which may be needed
#include <stdio.h>
#include <signal.h>

struct sigaction sigaction_structure;	// A data structure, filled in below

void catchSignal();				// Declaration only - definition below


int main (int argc, char *argv[])	// The 'root' programme; execution start
{

  // Set three fields in a predefined 'struct'
  sigaction_structure.sa_handler = &catchSignal;	// Pointer to a -function-
  sigemptyset(&sigaction_structure.sa_mask);	// Call defines 'empty' field
  sigaction_structure.sa_flags   = 0;		// No flags

  // Link the structure to signal "SIGFPE" (as generated by an illegal
  // mathematical operation.)
  sigaction(SIGFPE, &sigaction_structure, NULL); // Link


  printf("Trying to divide a number by 0!");

  int x = 1;
  int y = 0;
  int result = x/y;
}

//------------------------------------------------------------------------------

void catchSignal()
{
  printf("\nCaught signal of an an illegal mathematical operatio\n");

  exit(1);
}

//------------------------------------------------------------------------------
